name: RewardVaults
version: '${project.version}'
main: me.jammy.rewardvaults.RewardVaults
api-version: '1.20'

commands:
  rewardvault:
    description: Access the reward vault, and reward vault commands.
    usage: /<command> <args>
    permission: rewardvault.default
    aliases: [ rv, rewards ]
